const characters = [
    {
        id: 1,
        name: "Abaddon",
        image: "abaddon.png",
        rating: 4.9,
        reviews: 54,
    },
    {
        id: 2,
        name: "Alchemist",
        image: "alchemist.png",
        rating: 3.4,
        reviews: 32,
    },
    {
        id: 3,
        name: "Axe",
        image: "axe.png",
        rating: 4.4,
        reviews: 61,
    },
    {
        id: 4,
        name: "Beastmaster",
        image: "beastmaster.png",
        rating: 3.2,
        reviews: 35,
    },
    {
        id: 5,
        name: "Brewmaster",
        image: "brewmaster.png",
        rating: 4.6,
        reviews: 29,
    },
    {
        id: 6,
        name: "Bristleback",
        image: "bristleback.png",
        rating: 4.9,
        reviews: 67,
    },
    {
        id: 7,
        name: "Centaur Warrunner",
        image: "centaur_warrunner.png",
        rating: 4.3,
        reviews: 46,
    },
    {
        id: 8,
        name: "Chaos Knight",
        image: "chaos_knight.png",
        rating: 4.7,
        reviews: 43,
    },
    {
        id: 9,
        name: "Clockwerk",
        image: "clockwerk.png",
        rating: 3.9,
        reviews: 49,
    },
    {
        id: 10,
        name: "Doom",
        image: "doom.png",
        rating: 4.2,
        reviews: 39,
    },
    {
        id: 11,
        name: "Dragon Knight",
        image: "dragon_knight.png",
        rating: 3.8,
        reviews: 38,
    },
    {
        id: 12,
        name: "Earth Spirit",
        image: "earth_spirit.png",
        rating: 3.3,
        reviews: 33,
    },
    {
        id: 13,
        name: "Earthshaker",
        image: "earthshaker.png",
        rating: 4.5,
        reviews: 55,
    },
    {
        id: 14,
        name: "Elder Titan",
        image: "elder_titan.png",
        rating: 4.1,
        reviews: 28,
    },
    {
        id: 15,
        name: "Huskar",
        image: "huskar.png",
        rating: 3.7,
        reviews: 57,
    },
]

export default characters;